=== MuhammadShamrokh/EvolutionaryTimeTable/LogicEngine/src/ParsedClasses/ETT-V3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!-- edited with XMLSpy v2008 rel. 2 (http://www.altova.com) by mazuki (darksiderg) -->
<!--W3C Schema generated by XMLSpy v2008 rel. 2 (http://www.altova.com)-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="ETT-TimeTable">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-Teachers"/>
				<xs:element ref="ETT-Subjects"/>
				<xs:element ref="ETT-Classes"/>
				<xs:element ref="ETT-Rules"/>
			</xs:sequence>
			<xs:attribute name="hours" type="xs:int" use="required"/>
			<xs:attribute name="days" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Teaching">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-Teaches" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Teaches">
		<xs:complexType>
			<xs:attribute name="subject-id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Teachers">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-Teacher" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Teacher">
		<xs:complexType>
			<xs:all>
				<xs:element ref="ETT-Name"/>
				<xs:element ref="ETT-Teaching"/>
				<xs:element name="ETT-Working-Hours" type="xs:int"/>
			</xs:all>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Subjects">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-Subject" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Subject">
		<xs:complexType>
			<xs:attribute name="name" type="xs:string" use="required"/>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Study">
		<xs:complexType>
			<xs:attribute name="subject-id" type="xs:int" use="required"/>
			<xs:attribute name="hours" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Rules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-Rule" maxOccurs="unbounded"/>
			</xs:sequence>
			<xs:attribute name="hard-rules-weight" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-RuleId">
		<xs:simpleType>
			<xs:restriction base="xs:string">
				<xs:enumeration value="TeacherIsHuman"/>
				<xs:enumeration value="Singularity"/>
				<xs:enumeration value="Knowledgeable"/>
				<xs:enumeration value="DayOffTeacher"/>
				<xs:enumeration value="Sequentiality"/>
				<xs:enumeration value="DayOffClass"/>
				<xs:enumeration value="WorkingHoursPreference"/>
				<xs:enumeration value="Satisfactory"/>
			</xs:restriction>
		</xs:simpleType>
	</xs:element>
	<xs:element name="ETT-Rule">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-RuleId"/>
				<xs:element ref="ETT-Configuration" minOccurs="0"/>
			</xs:sequence>
			<xs:attribute name="type" use="required">
				<xs:simpleType>
					<xs:restriction base="xs:string">
						<xs:enumeration value="Hard"/>
						<xs:enumeration value="Soft"/>
					</xs:restriction>
				</xs:simpleType>
			</xs:attribute>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Requirements">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-Study" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Name" type="xs:string"/>
	<xs:element name="ETT-Descriptor">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-TimeTable"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Configuration" type="xs:string"/>
	<xs:element name="ETT-Classes">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="ETT-Class" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
	<xs:element name="ETT-Class">
		<xs:complexType>
			<xs:all>
				<xs:element ref="ETT-Name"/>
				<xs:element ref="ETT-Requirements"/>
			</xs:all>
			<xs:attribute name="id" type="xs:int" use="required"/>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== MuhammadShamrokh/EvolutionaryTimeTable/src/EX3-big.xml
<?xml version="1.0" encoding="UTF-8"?>
<ETT-Descriptor xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="ETT-V3.xsd">
	<ETT-TimeTable days="6" hours="8">
		<ETT-Teachers>
			<ETT-Teacher id="1">
				<ETT-Name>Mik Chol</ETT-Name>
				<ETT-Working-Hours>24</ETT-Working-Hours>				
				<ETT-Teaching>
					<ETT-Teaches subject-id="1"/>
					<ETT-Teaches subject-id="2"/>
				</ETT-Teaching>
			</ETT-Teacher>
			<ETT-Teacher id="3">
				<ETT-Name>Gilla Prisha</ETT-Name>
				<ETT-Working-Hours>36</ETT-Working-Hours>
				<ETT-Teaching>
					<ETT-Teaches subject-id="3"/>
				</ETT-Teaching>
			</ETT-Teacher>			
			<ETT-Teacher id="2">
				<ETT-Name>Maya Feba</ETT-Name>
				<ETT-Working-Hours>40</ETT-Working-Hours>				
				<ETT-Teaching>
					<ETT-Teaches subject-id="4"/>
					<ETT-Teaches subject-id="5"/>
				</ETT-Teaching>
			</ETT-Teacher>						
			<ETT-Teacher id="4">
				<ETT-Name>Boaz Orli</ETT-Name>
				<ETT-Working-Hours>10</ETT-Working-Hours>
				<ETT-Teaching>
					<ETT-Teaches subject-id="6"/>
					<ETT-Teaches subject-id="3"/>
					<ETT-Teaches subject-id="7"/>										
				</ETT-Teaching>
			</ETT-Teacher>	
			<ETT-Teacher id="6">
				<ETT-Name>Mali Veleze</ETT-Name>
				<ETT-Working-Hours>8</ETT-Working-Hours>
				<ETT-Teaching>
					<ETT-Teaches subject-id="5"/>
					<ETT-Teaches subject-id="1"/>
					<ETT-Teaches subject-id="7"/>					
				</ETT-Teaching>
			</ETT-Teacher>
			<ETT-Teacher id="5">
				<ETT-Name>Anita Franit</ETT-Name>
				<ETT-Working-Hours>44</ETT-Working-Hours>
				<ETT-Teaching>
					<ETT-Teaches subject-id="1"/>
					<ETT-Teaches subject-id="2"/>
					<ETT-Teaches subject-id="3"/>
					<ETT-Teaches subject-id="4"/>
					<ETT-Teaches subject-id="5"/>
					<ETT-Teaches subject-id="6"/>
				</ETT-Teaching>
			</ETT-Teacher>														
		</ETT-Teachers>
		<ETT-Subjects>
			<ETT-Subject id="1" name="Sifrut"/>
			<ETT-Subject id="3" name="Tanach"/>
			<ETT-Subject id="4" name="English"/>
			<ETT-Subject id="5" name="Math"/>
			<ETT-Subject id="2" name="Physics"/>
			<ETT-Subject id="6" name="Tongue"/>			
			<ETT-Subject id="7" name="Biology"/>			
		</ETT-Subjects>		
		<ETT-Classes>
			<ETT-Class id="1">
				<ETT-Name>Standart</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="1" hours="10"/>
					<ETT-Study subject-id="3" hours="12"/>
					<ETT-Study subject-id="6" hours="4"/>
					<ETT-Study subject-id="5" hours="4"/>
					<ETT-Study subject-id="2" hours="2"/>					
				</ETT-Requirements>
			</ETT-Class>
			<ETT-Class id="2">
				<ETT-Name>Nerds</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="1" hours="2"/>
					<ETT-Study subject-id="3" hours="2"/>
					<ETT-Study subject-id="6" hours="4"/>
					<ETT-Study subject-id="2" hours="12"/>
					<ETT-Study subject-id="4" hours="12"/>
					<ETT-Study subject-id="5" hours="12"/>
				</ETT-Requirements>
			</ETT-Class>			
			<ETT-Class id="3">
				<ETT-Name>Tikshoret</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="1" hours="4"/>
					<ETT-Study subject-id="3" hours="4"/>
					<ETT-Study subject-id="6" hours="6"/>
					<ETT-Study subject-id="2" hours="4"/>
					<ETT-Study subject-id="4" hours="4"/>					
				</ETT-Requirements>
			</ETT-Class>			
			<ETT-Class id="4">
				<ETT-Name>Biologit</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="1" hours="2"/>
					<ETT-Study subject-id="3" hours="2"/>
					<ETT-Study subject-id="6" hours="4"/>
					<ETT-Study subject-id="2" hours="6"/>
					<ETT-Study subject-id="4" hours="6"/>
					<ETT-Study subject-id="5" hours="6"/>
					<ETT-Study subject-id="7" hours="12"/>
				</ETT-Requirements>
			</ETT-Class>					
			<ETT-Class id="5">
				<ETT-Name>Science</ETT-Name>
				<ETT-Requirements>
					<ETT-Study subject-id="1" hours="3"/>
					<ETT-Study subject-id="3" hours="3"/>
					<ETT-Study subject-id="6" hours="3"/>
					<ETT-Study subject-id="2" hours="3"/>
					<ETT-Study subject-id="4" hours="3"/>
					<ETT-Study subject-id="5" hours="3"/>
					<ETT-Study subject-id="7" hours="3"/>
				</ETT-Requirements>
			</ETT-Class>								
		</ETT-Classes>
		<ETT-Rules hard-rules-weight="80">
			<ETT-Rule type="Hard">
				<ETT-RuleId>TeacherIsHuman</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Hard">
				<ETT-RuleId>Singularity</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Hard">
				<ETT-RuleId>Satisfactory</ETT-RuleId>
			</ETT-Rule>			
			<ETT-Rule type="Soft">
				<ETT-RuleId>Knowledgeable</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Soft">
				<ETT-RuleId>DayOffTeacher</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Soft">
				<ETT-RuleId>Sequentiality</ETT-RuleId>
				<ETT-Configuration>TotalHours=2</ETT-Configuration>				
			</ETT-Rule>				
			<ETT-Rule type="Soft">
				<ETT-RuleId>DayOffClass</ETT-RuleId>
			</ETT-Rule>
			<ETT-Rule type="Soft">
				<ETT-RuleId>WorkingHoursPreference</ETT-RuleId>
			</ETT-Rule>				
		</ETT-Rules>
	</ETT-TimeTable>	
</ETT-Descriptor>
